AWSTemplateFormatVersion: 2010-09-09
Description: Enable AWS CloudTrail. This template creates a CloudTrail trail, an Amazon S3 bucket where logs are published, and an Amazon SNS topic where notifications are sent.

Parameters:
  EnableLogFileValidation:
    Type: String
    Default: 'true'
    Description: Indicates whether CloudTrail validates the integrity of log files.
    AllowedValues:
      - 'true'
      - 'false'

  IncludeGlobalEvents:
    Type: String
    Default: 'true'
    Description: Indicates whether the trail is publishing events from global services, such as IAM, to the log files.
    AllowedValues:
      - 'true'
      - 'false'

  MultiRegion:
    Type: String
    Default: 'true'
    Description: Indicates whether the CloudTrail trail is created in the region in which you create the stack (false) or in all regions (true).
    AllowedValues:
      - 'true'
      - 'false'

  PublishToTopic:
    Type: String
    Default: 'false'
    Description: Indicates whether notifications are published to SNS.
    AllowedValues:
      - 'true'
      - 'false'

  PublishToCloudWatchLogs:
    Type: String
    Default: 'true'
    Description: Indicates whether notifications are published to CloudWatch Logs.
    AllowedValues:
      - 'true'
      - 'false'

  CloudWatchLogsGroupName:
    Type: String
    Default: 'cloudtrail/reinvent-2021-cop-322'
    Description: CloudWatchLogs Group name.

  TrailBucket:
    Type: String
    Description: Bucket name for logs.
    Default: 'true'

  LogsRetentionInDays:
    Description: 'Specifies the number of days you want to retain CloudTrail log events in the CloudWatch Logs.'
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

  pOrganizationCloudTrailKeyAlias:
    Default: reinvent-2021-cop-322-key
    Description: Organization CloudTrail KMS Key Alias
    Type: String

Conditions:
  IsMultiRegion: !Equals
    - !Ref MultiRegion
    - 'true'

  IsPublishToTopic: !Equals
    - !Ref PublishToTopic
    - 'true'

  IsPublishToCloudWatchLogs: !Equals
    - !Ref PublishToCloudWatchLogs
    - 'true'

Resources:
  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: reinvent-2021-cop-322
      S3BucketName: !Ref reinvent2021cop322bucket
      IsLogging: True
      EnableLogFileValidation: !Ref EnableLogFileValidation
      IncludeGlobalServiceEvents: !If
        - IsMultiRegion
        - True
        - !Ref IncludeGlobalEvents
      IsMultiRegionTrail: !Ref MultiRegion
      CloudWatchLogsLogGroupArn: !If
        - IsPublishToCloudWatchLogs
        - !GetAtt TrailLogGroup.Arn
        - !Ref AWS::NoValue
      CloudWatchLogsRoleArn: !If
        - IsPublishToCloudWatchLogs
        - !GetAtt TrailLogGroupRole.Arn
        - !Ref AWS::NoValue
      EventSelectors:
        -
          DataResources:
            -
              Type: AWS::S3::Object
              Values:
                - "arn:aws:s3:::"
  TrailLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Condition: IsPublishToCloudWatchLogs
    Properties:
      LogGroupName: !Ref CloudWatchLogsGroupName
      RetentionInDays: !Ref LogsRetentionInDays

  TrailLogGroupRole:
     Type: 'AWS::IAM::Role'
     Condition: IsPublishToCloudWatchLogs
     Properties:
       AssumeRolePolicyDocument:
         Version: '2012-10-17'
         Statement:
         - Sid: CloudTrailAssumeRole
           Effect: Allow
           Principal:
             Service: 'cloudtrail.amazonaws.com'
           Action: 'sts:AssumeRole'
       Policies:
       - PolicyName: 'cloudtrail-policy'
         PolicyDocument:
           Version: '2012-10-17'
           Statement:
           - Sid: AWSCloudTrailCreateLogStream
             Effect: Allow
             Action: 'logs:CreateLogStream'
             Resource: !GetAtt 'TrailLogGroup.Arn'
           - Sid: AWSCloudTrailPutLogEvents
             Effect: Allow
             Action: 'logs:PutLogEvents'
             Resource: !GetAtt 'TrailLogGroup.Arn'

  reinvent2021cop322bucket:
    Type: AWS::S3::Bucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: S3 access logging covered by CloudTrail S3 data events
    Properties:
      BucketName: !Sub "reinvent-2021-cop-322-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref reinvent2021encryptionkey
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  reinvent2021cop322bucketpolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref reinvent2021cop322bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:

          - Sid: DenyPutObject
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${reinvent2021cop322bucket}
              - !Sub arn:${AWS::Partition}:s3:::${reinvent2021cop322bucket}/*
            Condition:
              ForAnyValue:StringNotEquals:
                aws:CalledVia: cloudtrail.amazonaws.com

          - Sid: SecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${reinvent2021cop322bucket}
              - !Sub arn:${AWS::Partition}:s3:::${reinvent2021cop322bucket}/*
            Condition:
              Bool:
                "aws:SecureTransport": "false"

          - Sid: AWSBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action:
              - s3:GetBucketAcl
              - s3:ListBucket
            Resource: !Sub arn:${AWS::Partition}:s3:::${reinvent2021cop322bucket}

          - Sid: AWSBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:${AWS::Partition}:s3:::${reinvent2021cop322bucket}/*
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"


  reinvent2021encryptionkey:
    Type: AWS::KMS::Key
    Properties:
      Description: CloudTrail Key
      EnableKeyRotation: True
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Sub ${pOrganizationCloudTrailKeyAlias}
        Statement:
          -
            Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"
          -
            Sid: Allow CloudTrail and Config to encrypt logs
            Effect: Allow
            Principal:
              Service: ["cloudtrail.amazonaws.com", "config.amazonaws.com"]
            Action: kms:GenerateDataKey*
            Resource: "*"
          -
            Sid: Allow CloudTrail and Config to describe key
            Effect: Allow
            Principal:
              Service: ["cloudtrail.amazonaws.com", "config.amazonaws.com"]
            Action: kms:DescribeKey
            Resource: "*"
          -
            Sid: Allow alias creation during setup
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:CreateAlias
            Resource: "*"
            Condition:
              StringEquals:
                "kms:CallerAccount": !Sub ${AWS::AccountId}
                "kms:ViaService": !Sub cloudformation.${AWS::Region}.amazonaws.com


  rOrganizationCloudTrailKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${pOrganizationCloudTrailKeyAlias}
      TargetKeyId:
        !Ref reinvent2021encryptionkey

Outputs:
  cop322bucket:
    Value: !Ref reinvent2021cop322bucket
    Description: "S3 bucket for workshop"
    Export:
      Name: !Sub "cop322-s3-bucket"

